# Generated by Django 3.0.3 on 2020-03-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='eefault.jpg', upload_to='profile_pics'),
        ),
    ]
