# Generated by Django 3.0.3 on 2020-07-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
